### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by ShidouYuu** [Rikka-Kitani/Rikka-s-Research#1]
Hi,
After i drop mod in mods folder, only one thing i see is 3 keybinds in control settings.
No items in game, i don't see anything even in JEI, keys that are binded in options don't work.
In "mods" tab in main menu it looks as all other mods.

King Regards

**Comment by ReporterToTheMax** [comment]
This is supposed to be an invalid issue but Rikka apparently forgot to put in the desc. that the glove is not in creative mode tabs. The modid is rikkasresearch so just use give command. - ShelterRin

**Comment by Rikka-Kitani** [comment]
Sorry, I forgot to put a description related about elemental glove not listed in the creative tab. Might as well put it in the curseforge description. Thank you for noting me @ShidouYuu.
